Repository GSG-G11/nutritious-Saleh-Fady, pull requests merged in 2022-02, with the labels that each got.

#3 create file structure
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  public/css/style.css
  public/html/404.html
  public/html/500.html
  public/index.html
  public/js/dom.js
  public/js/logic.js
  public/js/test.js
  src/app.js
  src/controllers/index.js
  src/index.js
  src/routes/index.js
  src/test.js
Labels: Done

#5 initilize express server
  .eslintrc.js
  .eslintrc.json
  .vscode/settings.json
  package.json
  src/app.js
  src/index.js
Labels: approved

#7 handling fetch all fruites
  .eslintrc.json
  package-lock.json
  package.json
  src/app.js
  src/controllers/getFruites.js
  src/controllers/index.js
  src/routes/getFruites.js
  src/routes/index.js
Labels: Awaiting Review

#9 handling search for froute
  src/app.js
  src/controllers/index.js
  src/controllers/searchFruits.js
  src/routes/index.js
  src/routes/searchRouter.js
Labels: approved

#11 create 404 not found page
  public/html/404.html
  src/app.js
  src/controllers/404.js
  src/controllers/index.js
Labels: approved

#13 handling server error
  public/html/500.html
  src/app.js
  src/controllers/404.js
  src/controllers/index.js
  src/controllers/serverError.js
Labels: Awaiting Review

#15 update search controller checking if there is a fruit name
  src/controllers/searchFruits.js
Labels: approved

#17 limiting the data
  src/controllers/getFruites.js
  src/controllers/index.js
  src/controllers/searchFruits.js
Labels: Awaiting Review

#21 fetch data from back and render it in card
  public/index.html
  public/js/dom.js
  public/js/logic.js
  src/controllers/getFruites.js
Labels: approved

#24 style index.html container div and fruit card
  public/css/style.css
  public/index.html
  public/js/dom.js
Labels: approved

#25 adding form and title to index.html
  public/css/style.css
  public/index.html
Labels: Awaiting Review

#28 fix form input name
  public/index.html
Labels: Awaiting Review

#29 handling search form
  public/js/dom.js
  public/js/logic.js
  src/controllers/searchFruits.js
Labels: Awaiting Review

#31 adding loading spinner
  public/css/style.css
  public/index.html
  public/js/dom.js
Labels: Awaiting Review

#19 testing server routes
  package.json
  src/test.js
Labels: Awaiting Review

#33 fix style
  public/css/style.css
  src/controllers/getFruites.js
Labels: approved

#35 removing all console logs
  public/js/dom.js
  public/js/logic.js
  public/js/test.js
  src/controllers/searchFruits.js
  src/index.js
  src/routes/searchRouter.js
Labels: Awaiting Review

#36 add README.md file
  README.md
Labels: Done
